name : S3 Synchronisation Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@master
        with:
          args: --exclude '.git/*' --exclude '.github/*' --exclude 'README.md' --exclude '.gitignore' --exclude .gitattributes

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1 
          AWS_S3_BUCKET: 'mwaa-prod-logs'
          SOURCE_DIR: 'projects025'